# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='upwd',
            new_name='ConfirmPwd',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='uname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='uphonenumber',
            new_name='phonenumber',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
