# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0003_auto_20171129_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='confirmPwd',
        ),
    ]
